language: android
dist: trusty
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
    - build-tools-29.0.2
    - android-29

 script:
  - ./gradlew build connectedCheck

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+


